// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBBAd3xkzl8mjl5SmRBByG-3hA6yWceH88',
//     appId: '1:864507836729:web:11756d29fa35e336e110e8',
//     messagingSenderId: '864507836729',
//     projectId: 'workbuddy-testapp',
//     authDomain: 'workbuddy-testapp.firebaseapp.com',
//     storageBucket: 'workbuddy-testapp.firebasestorage.app',
//     measurementId: 'G-Y1CQRHQVDE',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD4M9eL95YqEX-soFW_Q4AHow3TkUDPBUQ',
//     appId: '1:864507836729:android:4e634264c6ba39e4e110e8',
//     messagingSenderId: '864507836729',
//     projectId: 'workbuddy-testapp',
//     storageBucket: 'workbuddy-testapp.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBeDO_7ggfVkc0QbRGS1PTmzmFNz70hxOc',
//     appId: '1:864507836729:ios:3616f85e6da7a7b7e110e8',
//     messagingSenderId: '864507836729',
//     projectId: 'workbuddy-testapp',
//     storageBucket: 'workbuddy-testapp.firebasestorage.app',
//     iosBundleId: 'com.example.widgetsIntroductionLiveCoding',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBeDO_7ggfVkc0QbRGS1PTmzmFNz70hxOc',
//     appId: '1:864507836729:ios:3616f85e6da7a7b7e110e8',
//     messagingSenderId: '864507836729',
//     projectId: 'workbuddy-testapp',
//     storageBucket: 'workbuddy-testapp.firebasestorage.app',
//     iosBundleId: 'com.example.widgetsIntroductionLiveCoding',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBBAd3xkzl8mjl5SmRBByG-3hA6yWceH88',
//     appId: '1:864507836729:web:d8913bb42ec06249e110e8',
//     messagingSenderId: '864507836729',
//     projectId: 'workbuddy-testapp',
//     authDomain: 'workbuddy-testapp.firebaseapp.com',
//     storageBucket: 'workbuddy-testapp.firebasestorage.app',
//     measurementId: 'G-L0L9404WPH',
//   );
// }
