name: workbuddy
description: "save time and money"
publish_to: 'none'
version: 0.03.17+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  flutter_exit_app: ^1.1.4
  dropdown_search: ^6.0.1
  searchfield: ^1.1.7
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.3
  sqflite: ^2.4.1
  path: ^1.9.0
  time_picker_spinner_pop_up: ^2.0.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  provider: ^6.1.2
  emojis: ^0.9.9
  shared_preferences: ^2.3.4
  intl: ^0.19.0
  package_info_plus: ^8.1.2
  flutter_localizations:
    sdk: flutter
  age_calculator: ^1.0.0
  money2: ^5.4.6
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_contacts: ^1.1.9+2
  #contacts_service: ^0.6.3
  #permission_handler: ^11.4.0

cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/workbuddy_icon_neon_green.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/workbuddy_icon_neon_green.png"
    background_color: "0xFFFFFFFF"
    theme_color: "0xFFFFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/workbuddy_icon_neon_green.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/workbuddy_icon_neon_green.png"
    remove_alpha_ios: true
  
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/icon/
   - assets/iconbuttons/
   - assets/company_logos/
   - assets/flags/
   - assets/sound/
   - assets/JOTHAsoft.FiveStars.db
   #- assets/JOTHAsoft.WorkBuddy.db