final emailUsersData = [
  {
    'id': 1,
    'firstName': 'Tony',
    'lastName': 'Reichert',
    'role': 'Vorstand',
    'team': 'Management',
    'status1': 'Kontakt',
    'status2': 'Privat',
    'category': 'B',
    'age': '29',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/1.png',
    'email': 'tony.reichert@example.com',
  },
  {
    'id': 2,
    'firstName': 'Zoey',
    'lastName': 'Hollyday',
    'role': 'Technische Leiterin',
    'team': 'Development',
    'status1': 'Kunde',
    'status2': 'Privat',
    'category': 'A',
    'age': '25',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/1.png',
    'email': 'zoey.hollyday@example.com',
  },
  {
    'id': 3,
    'firstName': 'Janette',
    'lastName': 'Fischer',
    'role': 'Senior Developer',
    'team': 'Development',
    'status1': 'Kontakt',
    'status2': 'Privat',
    'category': 'C',
    'age': '22',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/2.png',
    'email': 'jane.fischer@example.com',
  },
  {
    'id': 4,
    'firstName': 'William',
    'lastName': 'Shakes',
    'role': 'Marketingleiter',
    'team': 'Marketing',
    'status1': 'Kunde',
    'status2': 'B2B',
    'category': 'A',
    'age': '28',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/2.png',
    'email': 'william.shakes@example.com',
  },
  {
    'id': 5,
    'firstName': 'Kristen',
    'lastName': 'Küppers',
    'role': 'Verkaufs-Manager',
    'team': 'Sales',
    'status1': 'Kontakt',
    'status2': 'Einkauf',
    'category': 'B',
    'age': '24',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/3.png',
    'email': 'kristen.kueppers@example.com',
  },
  {
    'id': 6,
    'firstName': 'Brian',
    'lastName': 'Motley',
    'role': 'Personal-Manager',
    'team': 'Management',
    'status1': 'Kontakt',
    'status2': 'Privat',
    'category': 'B',
    'age:': '29',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/3.png',
    'email': 'brian.motley@example.com',
  },
  {
    'id': 7,
    'firstName': 'Michael',
    'lastName': 'Müller',
    'role': 'Designer',
    'team': 'Design',
    'status1': 'Kunde',
    'status2': 'Privat',
    'category': 'A',
    'age': '27',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/4.png',
    'email': 'michael.mueller@example.com',
  },
  {
    'id': 8,
    'firstName': 'Samantha',
    'lastName': 'Hollmann',
    'role': 'Studienrätin',
    'team': 'Education',
    'status1': 'Kontakt',
    'status2': 'Privat',
    'category': 'A',
    'age': '27',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/11.png',
    'email': 'samantha.hollmann@example.com',
  },
  {
    'id': 9,
    'firstName': 'Frank',
    'lastName': 'Schmidtke',
    'role': 'Finanzkaufmann',
    'team': 'Finance',
    'status1': 'Einkauf',
    'status2': 'B2B',
    'category': 'B',
    'age': '33',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/5.png',
    'email': 'frank.harrison@example.com',
  },
  {
    'id': 10,
    'firstName': 'Emma',
    'lastName': 'Holzmacher',
    'role': 'Operations-Manager',
    'team': 'Operations',
    'status1': 'Kontakt',
    'status2': 'B2B',
    'category': 'B',
    'age': '35',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/5.png',
    'email': 'emma.holzmacher@example.com',
  },
  {
    'id': 11,
    'firstName': 'Brandon',
    'lastName': 'Paulsen',
    'role': 'Junior Developer',
    'team': 'Development',
    'status1': 'Kontakt',
    'status2': 'Privat',
    'category': 'B',
    'age': '22',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/7.png',
    'email': 'brandon.paulsen@example.com',
  },
  {
    'id': 12,
    'firstName': 'Megan',
    'lastName': 'Holmaier',
    'role': 'Produkt-Manager',
    'team': 'Product',
    'status1': 'Kunde',
    'status2': 'B2B',
    'category': 'A',
    'age': '28',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/7.png',
    'email': 'megan.holmaier@example.com',
  },
  {
    'id': 13,
    'firstName': 'Oliver',
    'lastName': 'Petersen',
    'role': 'Security-Manager',
    'team': 'Security',
    'status1': 'Kontakt',
    'status2': 'B2B',
    'category': 'B',
    'age': '37',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/8.png',
    'email': 'oliver.petersen@example.com',
  },
  {
    'id': 14,
    'firstName': 'Grace',
    'lastName': 'Kelly',
    'role': 'Marketing Spezialist',
    'team': 'Marketing',
    'status1': 'Kontakt',
    'status2': 'B2B',
    'category': 'C',
    'age': '30',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/8.png',
    'email': 'grace.allen@example.com',
  },
  {
    'id': 15,
    'firstName': 'Noah',
    'lastName': 'Gomez',
    'role': 'IT-Spezialist',
    'team': 'I. Technology',
    'status1': 'Kunde',
    'status2': 'Privat',
    'category': 'B',
    'age': '31',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/9.png',
    'email': 'noah.carter@example.com',
  },
  {
    'id': 16,
    'firstName': 'Ava',
    'lastName': 'Bäcker',
    'role': 'Verkaufs-Manager',
    'team': 'Sales',
    'status1': 'Kontakt',
    'status2': 'Privat',
    'category': 'B',
    'age': '29',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/9.png',
    'email': 'ava.perez@example.com',
  },
  {
    'id': 17,
    'firstName': 'Liam',
    'lastName': 'Johnson',
    'role': 'Daten-Analyst',
    'team': 'Analysis',
    'status1': 'Kontakt',
    'status2': 'Privat',
    'category': 'B',
    'age': '28',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/11.png',
    'email': 'liam.johnson@example.com',
  },
  {
    'id': 18,
    'firstName': 'Sophia',
    'lastName': 'Schreiner',
    'role': 'Qualitäts-Analyst',
    'team': 'Testing',
    'status1': 'Kontakt',
    'status2': 'B2B',
    'category': 'B',
    'age': '27',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/4.png',
    'email': 'sophia.schreiner@example.com',
  },
  {
    'id': 19,
    'firstName': 'Lucas',
    'lastName': 'Schmid',
    'role': 'Administrator',
    'team': 'Information Technology',
    'status1': 'Kontakt',
    'status2': 'B2B',
    'category': 'A',
    'age': '32',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/12.png',
    'email': 'lucas.schmid@example.com',
  },
  {
    'id': 20,
    'firstName': 'Mia',
    'lastName': 'Maier',
    'role': 'Koordinator',
    'team': 'Operations',
    'status1': 'Kontakt',
    'status2': 'B2B',
    'category': 'B',
    'age': '26',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png',
    'email': 'mia.robinson@example.com',
  },
  {
    'id': 21,
    'firstName': 'Jürgen',
    'lastName': 'Hollmann',
    'role': 'Developer',
    'team': 'Flutter-Newbie',
    'status1': 'Kontakt',
    'status2': 'Privat',
    'category': 'A',
    'age': '60',
    'avatar': 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/12.png',
    'email': 'h.juergen.hollmann@gmail.com',
  },
];
