// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtQogbnkXkb70G8k_OSMi3B_UhNVWDIT4',
    appId: '1:374218152958:web:42c094b8a154d9a4363eaf',
    messagingSenderId: '374218152958',
    projectId: 'workbuddy-basic',
    authDomain: 'workbuddy-basic.firebaseapp.com',
    storageBucket: 'workbuddy-basic.firebasestorage.app',
    measurementId: 'G-YGGKZF8852',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBgL-PAwcjWvMnUA7UAkzMxgczqgL39Wc',
    appId: '1:374218152958:android:84a4f3f58d7c51ab363eaf',
    messagingSenderId: '374218152958',
    projectId: 'workbuddy-basic',
    storageBucket: 'workbuddy-basic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCAYV89vVyLsHLLcWcm8wDbERICy2dt-o',
    appId: '1:374218152958:ios:8bc52872ab3fe90b363eaf',
    messagingSenderId: '374218152958',
    projectId: 'workbuddy-basic',
    storageBucket: 'workbuddy-basic.firebasestorage.app',
    iosBundleId: 'com.example.workbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCAYV89vVyLsHLLcWcm8wDbERICy2dt-o',
    appId: '1:374218152958:ios:8bc52872ab3fe90b363eaf',
    messagingSenderId: '374218152958',
    projectId: 'workbuddy-basic',
    storageBucket: 'workbuddy-basic.firebasestorage.app',
    iosBundleId: 'com.example.workbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtQogbnkXkb70G8k_OSMi3B_UhNVWDIT4',
    appId: '1:374218152958:web:d358234e0daa07ec363eaf',
    messagingSenderId: '374218152958',
    projectId: 'workbuddy-basic',
    authDomain: 'workbuddy-basic.firebaseapp.com',
    storageBucket: 'workbuddy-basic.firebasestorage.app',
    measurementId: 'G-J0VD82PRVR',
  );

}