// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALUIH3nxrid-k6ZCplJwydCIw2Wa7QMkU',
    appId: '1:729420274996:web:5c6006deb6284c1f755961',
    messagingSenderId: '729420274996',
    projectId: 'workbuddy-test2',
    authDomain: 'workbuddy-test2.firebaseapp.com',
    storageBucket: 'workbuddy-test2.firebasestorage.app',
    measurementId: 'G-4X92YY6PQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyrY8daKs2odgqxgew9JPowtrp-lFRKHg',
    appId: '1:729420274996:android:94bc8b0f81d8acf4755961',
    messagingSenderId: '729420274996',
    projectId: 'workbuddy-test2',
    storageBucket: 'workbuddy-test2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDiSXEVZY9qt9VBNtyzdAyfwOKIvEfz7w',
    appId: '1:729420274996:ios:a04c6d243949ba82755961',
    messagingSenderId: '729420274996',
    projectId: 'workbuddy-test2',
    storageBucket: 'workbuddy-test2.firebasestorage.app',
    iosBundleId: 'com.example.widgetsIntroductionLiveCoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDiSXEVZY9qt9VBNtyzdAyfwOKIvEfz7w',
    appId: '1:729420274996:ios:a04c6d243949ba82755961',
    messagingSenderId: '729420274996',
    projectId: 'workbuddy-test2',
    storageBucket: 'workbuddy-test2.firebasestorage.app',
    iosBundleId: 'com.example.widgetsIntroductionLiveCoding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALUIH3nxrid-k6ZCplJwydCIw2Wa7QMkU',
    appId: '1:729420274996:web:c2e5e4f30b620f97755961',
    messagingSenderId: '729420274996',
    projectId: 'workbuddy-test2',
    authDomain: 'workbuddy-test2.firebaseapp.com',
    storageBucket: 'workbuddy-test2.firebasestorage.app',
    measurementId: 'G-2M2VDBLE4V',
  );

}